Repository exoego/rspec-openapi, pull requests merged in 2023-05, with the labels that each got.

#106 Enable coverage report
  .github/workflows/test.yml
  .simplecov_spawn.rb
  Gemfile
  spec/spec_helper.rb
Labels: chore

#115 Add coverage badge
  README.md
Labels: chore

#116 Add instructions for minitest triggered yaml generation.
  README.md
Labels: documentation

#117 Fix multiple uploaded files examples
  lib/rspec/openapi/schema_builder.rb
  spec/integration_tests/rails_test.rb
  spec/rails/app/controllers/images_controller.rb
  spec/rails/config/routes.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
  spec/requests/rails_spec.rb
Labels: bug

#114 Add required request params to metadata
  README.md
  lib/rspec/openapi/record.rb
  lib/rspec/openapi/record_builder.rb
  lib/rspec/openapi/schema_builder.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
  spec/rails/doc/smart/expected.yaml
  spec/requests/rails_smart_merge_spec.rb
Labels: enhancement, breakingchange
