Repository exoego/rspec-openapi, pull requests merged in 2023-12, with the labels that each got.

#150 Add ability to configure which path params to ignore
  README.md
  lib/rspec/openapi.rb
  lib/rspec/openapi/record_builder.rb
Labels: enhancement

#151 Setup Dependabot to update github action
  .github/dependabot.yml
Labels: chore

#149 Merge parameter data to preserve description in manually edited Openapi spec
  lib/rspec/openapi/schema_merger.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
Labels: bug

#147 Add custom title
  README.md
  lib/rspec/openapi.rb
  lib/rspec/openapi/result_recorder.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
  spec/requests/rails_spec.rb
Labels: enhancement

#148 Add ability to define custom summary and tags builders
  README.md
  lib/rspec/openapi.rb
  lib/rspec/openapi/record_builder.rb
Labels: enhancement

#155 Sort paths lexicographically so the order of paths is more stable and predictable
  lib/rspec/openapi/result_recorder.rb
  lib/rspec/openapi/schema_cleaner.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
Labels: enhancement, breakingchange

#154 requestBody should not merge requestBody from error examples
  lib/rspec/openapi/schema_builder.rb
  spec/integration_tests/rails_test.rb
  spec/integration_tests/roda_test.rb
  spec/rails/app/controllers/tables_controller.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
  spec/requests/rails_spec.rb
Labels: enhancement

#156 v0.10.0 release note
  CHANGELOG.md
Labels: chore

#157 releasing v0.10.0
  lib/rspec/openapi/version.rb
Labels: chore

#163 Sort HTTP methods, response status codes, and contents lexicographically
  lib/rspec/openapi.rb
  lib/rspec/openapi/result_recorder.rb
  lib/rspec/openapi/schema_cleaner.rb
  lib/rspec/openapi/schema_sorter.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
Labels: enhancement
