Repository exoego/rspec-openapi, pull requests merged in 2024-04, with the labels that each got.

#203 README: More badges
  README.md
Labels: chore

#206 Introduce Post-Processing Hook for OpenAPI Spec Customization
  README.md
  lib/rspec/openapi.rb
  lib/rspec/openapi/result_recorder.rb
  spec/apps/rails/doc/openapi.json
  spec/apps/rails/doc/openapi.yaml
  spec/integration_tests/rails_test.rb
Labels: enhancement

#207 Fix image path in README
  README.md
Labels: documentation

#205 Add support hanami router
  lib/rspec/openapi.rb
  lib/rspec/openapi/extractors.rb
  lib/rspec/openapi/extractors/hanami.rb
  lib/rspec/openapi/extractors/rack.rb
  lib/rspec/openapi/extractors/rails.rb
  lib/rspec/openapi/minitest_hooks.rb
  lib/rspec/openapi/record_builder.rb
  lib/rspec/openapi/rspec_hooks.rb
  lib/rspec/openapi/shared_hooks.rb
  spec/apps/hanami/doc/openapi.json
  spec/apps/hanami/doc/openapi.yaml
  spec/requests/hanami_spec.rb
Labels: enhancement

#208 Address rubocop issues
  .rubocop_todo.yml
  lib/rspec/openapi/shared_hooks.rb
Labels: chore

#209 Releasing v0.17.0
  lib/rspec/openapi/version.rb
Labels: chore

#211 Fix code comment
  lib/rspec/openapi/extractors/hanami.rb
  lib/rspec/openapi/extractors/rack.rb
  lib/rspec/openapi/extractors/rails.rb
Labels: documentation

#214 Style/MapIntoArray: Use map instead of each to map elements into an array
  lib/rspec/openapi/schema_builder.rb
Labels: chore

#215 Bump rails
  .github/workflows/test.yml
  Gemfile
Labels: chore

#212 Don't rescue when `require 'rspec/openapi/*'` raises `LoadError`
  lib/rspec/openapi.rb
Labels: chore

#217 Dont' log missing Rails/Hanami unless DEBUG
  lib/rspec/openapi.rb
Labels: enhancement

#213 Add support mounted rack app for rails and hanami
  lib/rspec/openapi/extractors/hanami.rb
  lib/rspec/openapi/extractors/rails.rb
  spec/apps/hanami/config/routes.rb
  spec/apps/hanami/doc/openapi.json
  spec/apps/hanami/doc/openapi.yaml
  spec/apps/hanami/lib/rack_test/app.rb
  spec/apps/rails/config/initializers/rack_test.rb
  spec/apps/rails/config/routes.rb
  spec/apps/rails/doc/openapi.json
  spec/apps/rails/doc/openapi.yaml
  spec/apps/rails/lib/rack_test/app.rb
  spec/integration_tests/rails_test.rb
  spec/requests/hanami_spec.rb
  spec/requests/rails_spec.rb
Labels: enhancement

#218 Releasing V0.18.0
  .github/release.yaml
  lib/rspec/openapi/version.rb
Labels: chore

#221 regression: Symbol parameters in routing causes error on Rails
  .rubocop_todo.yml
  lib/rspec/openapi/extractors.rb
  lib/rspec/openapi/extractors/hanami.rb
  lib/rspec/openapi/extractors/rails.rb
  spec/apps/rails/config/routes.rb
Labels: bug

#225 test: elide unchanged lines in large hash
  spec/spec_helper.rb
Labels: chore

#226 regression: non-numeric path parameter raises on Rails
  lib/rspec/openapi/extractors/hanami.rb
  lib/rspec/openapi/extractors/rails.rb
  spec/apps/hanami/app/actions/sites/show.rb
  spec/apps/hanami/app/actions/sites/site_action.rb
  spec/apps/hanami/app/actions/sites/site_repository.rb
  spec/apps/hanami/config/routes.rb
  spec/apps/hanami/doc/openapi.json
  spec/apps/hanami/doc/openapi.yaml
  spec/apps/rails/app/controllers/sites_controller.rb
  spec/apps/rails/config/routes.rb
  spec/apps/rails/doc/openapi.json
  spec/apps/rails/doc/openapi.yaml
  spec/integration_tests/rails_test.rb
  spec/requests/hanami_spec.rb
  spec/requests/rails_spec.rb
Labels: bug

#229 Releasing v0.18.2
  lib/rspec/openapi/version.rb
Labels: chore

#220 Refactor global DEBUG_ENABLED to module-based configuration
  lib/rspec/openapi.rb
Labels: refactoring
