Repository exoego/rspec-openapi, pull requests merged in 2024-03, with the labels that each got.

#179 Use GitHub releases as a single source of changelog
  CHANGELOG.md
  rspec-openapi.gemspec
Labels: chore

#181 Releasing v0.13.0
  lib/rspec/openapi/version.rb
Labels: chore

#184 path-level exclusion
  README.md
  lib/rspec/openapi.rb
  lib/rspec/openapi/record_builder.rb
  spec/integration_tests/rails_test.rb
  spec/integration_tests/roda_test.rb
  spec/rails/app/controllers/masters/extensions_controller.rb
  spec/rails/config/routes.rb
  spec/requests/rails_spec.rb
  spec/requests/roda_spec.rb
Labels: enhancement

#186 Suppress rubocop extension suggestion
  .rubocop.yml
Labels: chore

#187 doc: Fixed broken link
  README.md
Labels: documentation

#188 Fix minitest hook failing on error log
  lib/rspec/openapi/minitest_hooks.rb
Labels: bug

#191 Drop Ruby 2.5 and 2.6 support
  .github/workflows/rubocop.yml
  .github/workflows/test.yml
  .rubocop.yml
  lib/rspec/openapi/minitest_hooks.rb
  lib/rspec/openapi/rspec_hooks.rb
  lib/rspec/openapi/schema_merger.rb
  rspec-openapi.gemspec
Labels: chore

#192 Delete unneeded CI step
  .github/workflows/test.yml
Labels: chore

#189 Use raw HTML content so example can be generated with Rails 7.1+
  .rubocop_todo.yml
  lib/rspec/openapi/record_builder.rb
  lib/rspec/openapi/schema_builder.rb
  spec/rails/app/controllers/pages_controller.rb
  spec/rails/config/routes.rb
  spec/rails/doc/smart/expected.yaml
  spec/requests/rails_smart_merge_spec.rb
Labels: bug

#193 fix: Remove content field if no content
  lib/rspec/openapi/schema_builder.rb
  spec/rails/doc/smart/expected.yaml
  spec/requests/rails_smart_merge_spec.rb
Labels: bug

#198 Fixes invalid merge logic
  lib/rspec/openapi.rb
  lib/rspec/openapi/components_updater.rb
  lib/rspec/openapi/hash_helper.rb
  lib/rspec/openapi/key_transformer.rb
  lib/rspec/openapi/record_builder.rb
  lib/rspec/openapi/schema_cleaner.rb
  lib/rspec/openapi/schema_file.rb
  lib/rspec/openapi/schema_merger.rb
  lib/rspec/openapi/schema_sorter.rb
  spec/rspec/scheme_merger_spec.rb
Labels: bug

#196 Generate empty request body
  lib/rspec/openapi/schema_builder.rb
  spec/rails/app/controllers/users_controller.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
  spec/rails/doc/smart/expected.yaml
  spec/requests/rails_smart_merge_spec.rb
Labels: bug

#199 Remove debug log
  lib/rspec/openapi/components_updater.rb
Labels: chore

#201 Support deprecated attribute
  lib/rspec/openapi/record.rb
  lib/rspec/openapi/record_builder.rb
  lib/rspec/openapi/schema_builder.rb
  spec/rails/doc/openapi.json
  spec/rails/doc/openapi.yaml
  spec/requests/rails_spec.rb
Labels: enhancement
